<?php
$urls = array(
    'https://www.facto.hk',
    'https://www.facto.hk/about',
	'https://www.facto.hk/projects',
	'https://www.facto.hk/blog',
	'https://www.facto.hk/careers',
	'https://www.facto.hk/contact',
	'https://www.facto.hk/projects/dripen',
	'https://www.facto.hk/projects/typoss',
	'https://www.facto.hk/projects/outap',
	'https://www.facto.hk/projects/chicstall',
	'https://www.facto.hk/projects/shiguangmeng',
	'https://www.facto.hk/projects/aqara',
	'https://www.facto.hk/projects/qfgift',
	'https://www.facto.hk/projects/jiuchensiji',
	'https://www.facto.hk/projects/landlane',
	'https://www.facto.hk/projects/cmoffer',
	'https://www.facto.hk/projects/setshoot',
	'https://www.facto.hk/projects/cmb',
	'https://www.facto.hk/projects/jieguang',
	'https://www.facto.hk/capabilities/web-development',
	'https://www.facto.hk/capabilities/content',
	'https://www.facto.hk/capabilities/digital-strategy',
	'https://www.facto.hk/capabilities/web-design',
	'https://www.facto.hk/capabilities/branding',
	'https://www.facto.hk/careers/marketing-manager',
	'https://www.facto.hk/blog/category/tech',
	'https://www.facto.hk/blog/category/marketing',
	'https://www.facto.hk/blog/category/design',
	'https://www.facto.hk/blog/web3-is-the-buzz-the-new-biz',
	'https://www.facto.hk/blog/five-problems-facing-digital-marketers-in-2023',
	'https://www.facto.hk/blog/professional-website-design-matters',
	'https://www.facto.hk/en',
    'https://www.facto.hk/en/about',
	'https://www.facto.hk/en/projects',
	'https://www.facto.hk/en/blog',
	'https://www.facto.hk/en/careers',
	'https://www.facto.hk/en/contact',
	'https://www.facto.hk/en/projects/dripen',
	'https://www.facto.hk/en/projects/typoss',
	'https://www.facto.hk/en/projects/outap',
	'https://www.facto.hk/en/projects/chicstall',
	'https://www.facto.hk/en/projects/shiguangmeng',
	'https://www.facto.hk/en/projects/aqara',
	'https://www.facto.hk/en/projects/qfgift',
	'https://www.facto.hk/en/projects/jiuchensiji',
	'https://www.facto.hk/en/projects/landlane',
	'https://www.facto.hk/en/projects/cmoffer',
	'https://www.facto.hk/en/projects/setshoot',
	'https://www.facto.hk/en/projects/cmb',
	'https://www.facto.hk/en/projects/jieguang',
	'https://www.facto.hk/en/capabilities/web-development',
	'https://www.facto.hk/en/capabilities/content',
	'https://www.facto.hk/en/capabilities/digital-strategy',
	'https://www.facto.hk/en/capabilities/web-design',
	'https://www.facto.hk/en/capabilities/branding',
	'https://www.facto.hk/en/careers/marketing-manager',
	'https://www.facto.hk/en/blog/category/tech',
	'https://www.facto.hk/en/blog/category/marketing',
	'https://www.facto.hk/en/blog/category/design',
	'https://www.facto.hk/en/blog/web3-is-the-buzz-the-new-biz',
	'https://www.facto.hk/en/blog/five-problems-facing-digital-marketers-in-2023',
	'https://www.facto.hk/en/blog/professional-website-design-matters',
	'https://www.facto.hk/blog/mj-generated-images-vol-1/'
);
$api = 'http://data.zz.baidu.com/urls?site=https://www.facto.hk&token=btTX2kDFHhX6iUUC';
$ch = curl_init();
$options =  array(
    CURLOPT_URL => $api,
    CURLOPT_POST => true,
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_POSTFIELDS => implode("\n", $urls),
    CURLOPT_HTTPHEADER => array('Content-Type: text/plain'),
);
curl_setopt_array($ch, $options);
$result = curl_exec($ch);
echo $result;
?>